- fixed driver to use on ia64 systems. there is no framebuffer   available but the vesa driver is working now (#34909) - fixed possible loop at installation. handle different exit codes   from testX in scripts/YaST2. The needed changes to testX have   been made within the sax2 package (#36794)
svn path=/trunk/installation/; revision=16942

diff --git a/scripts/YaST2 b/scripts/YaST2
--- a/scripts/YaST2
+++ b/scripts/YaST2
@@ -125,6 +125,26 @@ function y2cc_ncurses()
     fi
 }
 
+function wait_for_x11()
+{
+	while kill -0 $xserver_pid 2>/dev/null ; do
+		sleep 1
+		if test -e /tmp/.X11-unix/X0 && test -x $TESTX ; then
+			$TESTX "$YaST2color" 2>/dev/null
+			# exit code 1 -> XOpenDisplay failed...
+			if test $? = 1;then
+				continue
+			fi
+			# exit code 2 -> color or dimensions doesn't fit...
+			if test $? = 2;then
+				break;
+			fi
+			server_running=1
+			break
+		fi
+	done
+}
+
 # set splash progress bar to 90%
 [ -f /proc/splash ] && echo "show $((90*65534/100))" >/proc/splash
 
@@ -197,7 +217,7 @@ if [ "`uname -m`" != alpha  ]; then
             XVersion=4
             XServer=fbdev
           fi
-          else
+        else
           if [ -e $x11_driver_dir/vga_drv.o ] ; then
             XVersion=4
             XServer=vga
@@ -206,6 +226,10 @@ if [ "`uname -m`" != alpha  ]; then
                 XServer=
                 Textmode=1
             fi
+          fi
+          if [ -e $x11_driver_dir/vesa_drv.o -a "`uname -m`" = ia64 ] ; then
+            XVersion=4
+            XServer=vesa
           fi
         fi
 #     fi
@@ -225,6 +249,7 @@ else
     [ -f "$x11_driver_dir/${XServer}_drv.o" ] && xsrvarg='0'
     [ "$XServer" = vga ] && xsrvarg='vga'
     [ "$XServer" = fbdev ] && xsrvarg='fbdev'
+    [ "$XServer" = vesa ] && xsrvarg='vesa'
     [ "$XServer" = fbdev -a ! "$fbdev_ok" ] && xsrvarg='vga'
 
     # use visual PseudoColor on VGA
@@ -380,13 +405,7 @@ if [ "$update" ] ; then
   X -deferglyphs 16 2>/dev/tty8 1>&2 vt07 &
   xserver_pid=$!
   # wait for the X server to come up
-  while kill -0 $xserver_pid 2>/dev/null ; do
-    sleep 1
-    if test -e /tmp/.X11-unix/X0 && test -x $TESTX && $TESTX "$YaST2color" 2>/dev/null ; then
-      server_running=1
-      break
-    fi
-  done
+  wait_for_x11
 else
   if [ "$xsrv" ] ; then
     # try to work around the mode line problem:
@@ -405,13 +424,7 @@ else
       X $xpseudo -xf86config /etc/X11/XF86Config_31.5k -deferglyphs 16 2>/dev/tty8 1>&2 vt07 &
       xserver_pid=$!
       # wait for the X server to come up
-      while kill -0 $xserver_pid 2>/dev/null ; do
-        sleep 1
-        if test -e /tmp/.X11-unix/X0 && test -x $TESTX && $TESTX "$YaST2color" 2>/dev/null ; then
-          server_running=1
-          break
-        fi
-      done
+      wait_for_x11
     fi
 
     if [ ! "$server_running" ]; then
